hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
  readdir:
    - condition:
        not:
          file_content_contains:
            path: "ip_addr.txt"
            expected_substring: "(?i)236"
            # expected_substring: "(?i)_ _ _\\.236._ _ _\\._ _"
      actions:
        - value: ""
    # - condition:
    #     not:
    #       file_content_contains:
    #         path: "ip_addr.txt"
    #         expected_substring: "(?i)_ _ _\\.236._ _ _\\._ _"
    #   actions:
    #     - value: ""

  getattr:
    - condition:
        not:
          file_content_contains:
            path: "ip_addr.txt"
            expected_substring: "(?i)236"
            # expected_substring: "(?i)_ _ _\\.236._ _ _\\._ _"
      actions:
        - value: null
    # - condition:
    #     not:
    #       file_content_contains:
    #         path: "ip_addr.txt"
    #         expected_substring: "(?i)_ _ _\\.236._ _ _\\._ _"
    #   actions:
    #     - value: ""