hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
  getattr:
    - condition: always
      actions:
        - value: { mode: 040000}
  access:
    - condition: always
      actions:
        - error: access_denied