hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
        
  readdir:
    - condition:
        not:
          all:
            - file_exists: "../../../shared_folder/blue_wire"
            - file_exists: "../../../shared_folder/green_wire"
            - file_exists: "../../../shared_folder/red_wire"
            - file_exists: "../../../shared_folder/wire_cutter"
      actions:
        - value: null

  getattr:
    - condition:
        not:
          all:
            - file_exists: "../../../shared_folder/blue_wire"
            - file_exists: "../../../shared_folder/green_wire"
            - file_exists: "../../../shared_folder/red_wire"
            - file_exists: "../../../shared_folder/wire_cutter"
      actions:
        - error: no_exist