hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied

  getattr:
    - condition: always
      actions:
        - value:
            mode: 32768
            size: 989898 

  read:
    - condition:
        offset:
          threshold: 989898
          mode: gte
      actions:
        - content_text: " 03/04  server unit #4 - loaned to: [redacted] \n 03/04  server unit #4 - checked into: Server_Closet - Second_Floor/________ \n loan ref: 236 \n log: Server_Closet/unit_04_log.txt \n service history: Chris_Bingham_Office/.service_record \n\n TO DO: \n [1] send all equipment in inventory/ to player in Wilkinson (do as individual files not the whole folder) \n \t\t [path from inventory/ = ../../../../shared_folder/] \n [2] look at Chris_Bingham_Office/.service_record \n"


# *** read at offset ***

# on cat - gives permission denied,
# reading at offset gives:

# 03/04  server unit #4 — loaned to: [redacted]
# 03/04  server unit #4 — checked into: Server_Closet — Second_Floor/______
# loan ref: 236
# log: Server_Closet/unit_04_log.txt
# service history: Chris_Bingham_Office/.service_record

# TO DO:
# [1] send 'Wires' and 'Write Cutters' to Wilkinson's Garage Lab
# [2] look at Chris_Bingham_Office/.service_record
