hooks:
  getattr:
    - condition: always
      actions:
        - value: null
  readdir:
    - condition: always
      actions:
        - value: null
  rmdir: 
    - condition: always
      actions:
        - allow: false
        