hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
        
  readdir:
    - condition:
        not:
          file_exists: "../../../shared_folder/ip_addr.txt"
      actions:
        - value: null

  getattr:
    - condition:
        not:
          file_exists: "../../../shared_folder/ip_addr.txt"
      actions:
        - error: no_exist