hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
  readdir:
    - condition:
        not:
          file_content_contains:
            path: "../Mark_Palmeri_Office/checkpoint_1_answer.txt"
            expected_substring: "(?i)Annex_Hallway"
      actions:
        - value: ""
        
  getattr:
    - condition:
        not:
          file_content_contains:
            path: "../Mark_Palmeri_Office/checkpoint_1_answer.txt"
            expected_substring: "(?i)Annex_Hallway"
      actions:
        - value: null