hooks:
  unlink:
    - condition: always
      actions:
        - allow: false
  rmdir:
    - condition: always
      actions:
        - allow: false
  readdir:
    - condition:
        not:
          file_exists: "../../../../shared_folder/RAID_Paper_Poster.txt"
      actions:
        - value: null

  getattr:
    - condition: always
      actions:
        - value:
            size: 989898

  read:
    - condition:
        offset:
          threshold: 989898
          mode: gte
      actions:
        - content_text: " badge: annex rear [03/04 02:11], \n\t Hudson front entrance [03/04 01:37] \n ref: 'ECE_Display_Board/access_log.txt'\n"