hooks:
  getattr: &hide_not_match
    - condition: 
        not:
          file_content_matches:
            path: search.me
            expected_content: "\\s*Bletsch\\s*"
      actions:
        - value: null
  readdir: *hide_not_match
  unlink: &never_allow
    - condition: always
      actions: [{"allow": False}]
  write: *never_allow