
hooks:
  getattr: &hide_not_match
    - condition: 
        not:
          file_content_matches:
            path: search.me
            expected_content: "\\s*Board\\s*"
      actions:
        - error: no_exist
  readdir: *hide_not_match
  unlink: &never_allow
    - condition: always
      actions: [{error: access_denied}]
  write: *never_allow
