hooks:
  readdir:
    - condition:
        not:
          file_content_contains:
            path: "terrace/door/panel.txt"
            expected_substring: "status: unlocked"
      actions:
        - value: ""

  getattr:
    - condition:
        not:
          file_content_contains:
            path: "terrace/door/panel.txt"
            expected_substring: "status: unlocked"
      actions:
        - error: no_exist

  access:
    - condition:
        not:
          file_content_contains:
            path: "terrace/door/panel.txt"
            expected_substring: "status: unlocked"
      actions:
        - error: access_denied