hooks:
  unlink:
    - condition: always
      actions:
        - error: access_denied
  rmdir:
    - condition: always
      actions:
        - error: access_denied
  readdir:
    - condition:
        not:
          file_content_contains:
            path: "Second_Floor/Annex/Hallway/checkpoint_2_answer.txt"
            expected_substring: "(?i)ECE_Display_Board/access_log\\.txt"
      actions:
        - value: null
  getattr:
    - condition:
        not:
          file_content_contains:
            path: "Second_Floor/Annex/Hallway/checkpoint_2_answer.txt"
            expected_substring: "(?i)ECE_Display_Board/access_log\\.txt"
      actions:
        - error: no_exist