hooks:
  getattr:
    - condition: &proctor_absent
        not:
          file_content_contains:
            path: 'proctor_tag'
            expected_substring: 'You may grade presentations.'
      actions:
        - value: { 'mode': 0100000 }
  access:
    - condition: *proctor_absent
      actions:
        - error: access_denied
  read:
    - condition: *proctor_absent
      actions:
        - error: access_denied
  write: &disallow
    - condition: always
      actions:
        - error: access_denied
  truncate: *disallow
  unlink: *disallow