hooks:
  read:
    - condition:
        not:
          file_content_contains:
            path: 'proctor_tag'
            expected_substring: 'You may grade presentations.'
      actions:
        - content_text: "hm, you're not my proctor...\n"
    
  write: &disallow
    - condition: always
      actions:
        - error: access_denied
  truncate: *disallow
  unlink: *disallow