hooks:
  unlink:
    - condition: always
      actions:
        - allow: false
  rmdir:
    - condition: always
      actions:
        - allow: false
  readdir:
    - condition: always
      actions:
        - value: null